version: "3.4"
services:
  mysql:
    restart: always
    build: tools/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=authentication
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=BambooTuna
      - MYSQL_PASSWORD=pass
  server:
    restart: always
    image: bambootuna/authenticationroutersupport:latest
    ports:
      - 8080:8080
    environment:
      - MYSQL_DATABASE=authentication
      - MYSQL_HOST=mysql
    depends_on:
      - mysql
